backend:
  name: github
  repo: fjlisbona/my-react-app
  branch: gh-pages
  base_url: https://www.patricialisbona.es
  auth_endpoint: /auth
  auth_type: pkce
  app_id: Ov23ligZZJjj2Yt6PkSR
  api_root: https://api.github.com
site_url: https://www.patricialisbona.es

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Publicaciones"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
